name: scala-smtlib CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    # the CI is small enough that we can run on draft PRs as well without issue
    # if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 21 ]
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS_TMP_DIR: ./tmp_java
      JAVA_OPTS: -Xss64M -Xms1024M -Xmx8G -Djava.io.tmpdir=$JAVA_OPTS_TMP_DIR
      JVM_OPTS:  -Xss64M -Xms1024M -Xmx8G -Djava.io.tmpdir=$JAVA_OPTS_TMP_DIR
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - name: Install and unpack sbt
      run: |
        ./scripts/install_sbt.sh
        echo "PATH=./sbt/bin/:$PATH" >> "$GITHUB_ENV"
    - name: Prepare temp folder
      run: rm -rf $JAVA_OPTS_TMP_DIR && mkdir -p $JAVA_OPTS_TMP_DIR
    - name: Install solvers
      run: ./scripts/install_solvers.sh $GITHUB_WORKSPACE/.local/bin
    - name: Add solvers to PATH
      run: echo "$GITHUB_WORKSPACE/.local/bin" >> $GITHUB_PATH
    - name: Test solvers availability
      run: cvc5 --version && z3 --version && cvc4 --version
    - name: Run Tests
      run: sbt -Dtest-parallelism=10 -batch test
    - name: Run integration tests
      run: sbt -Dtest-parallelism=10 -batch it:test
    - name: Clean up
      run: rm -rf $JAVA_OPTS_TMP_DIR
